version: 2
jobs:
  code-quality-and-unit-tests:
    docker:
      - image: circleci/php:7.2-apache-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Run code quality checks
          command: |
            composer install --ansi --no-suggest 2>&1 | sed --unbuffered -e 's#\x08\+# #g' -e 's#\(Downloading (\x1b\[[0-9]\+m[0-9]\?[0-9]%\x1b\[[0-9]\+m)\)\+##g'
            composer lint
            composer phpcs
            composer phpstan
            composer phpunit

workflows:
  version: 2
  workflow-code-quality-and-unit-tests:
    jobs:
      - code-quality-and-unit-tests
